---
# tasks file for Kibana_install
- name: copy config 
  copy:
       src: /home/tandem/Graduate-work/ansible/playbooks/kibana.config.yml
       dest: /home/tandem/kibana.yml
       owner: tandem
       group: docker
       mode: 0774

- name: Deploy Kibana
  community.docker.docker_container:
        name: kibana
        image: kibana:7.16.1
        ports: 
          - "5601:5601"
        volumes:
          - /home/tandem/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
        
        restart_policy: always