---
- name: Install nginx
  hosts: web
  become: yes
  gather_facts: yes
  roles:
  - name: nginx


- name: Install zabbix
  hosts: zabbix
  become: yes
  gather_facts: yes
  roles:
  - name: zabbix_install

- name: Install zabbix_agent
  hosts: [web, elk, bastion-host]
  become: yes
  gather_facts: yes
  roles:
  - name: zabbix_agent


- name: Install docker
  hosts: [ elk, web ]
  become: yes
  gather_facts: yes
  roles:
  - name: Docker_install

- name: Install Elasticksearch
  hosts: elastic
  become: yes
  gather_facts: yes
  roles:
  - name: Elasticsearch_install


- name: Install Kibana
  hosts: kibana
  become: yes
  gather_facts: yes
  roles:
  - name: Kibana_install

- name: Install Filebeat
  hosts: web
  become: yes
  gather_facts: yes
  roles:
  - name: Filebeat_install