server.name: Kibana
server.host: 0.0.0.0
server.publicBaseUrl: "http://localhost:5601"
monitoring.ui.container.elasticsearch.enabled: true

elasticsearch.hosts: ["http://192.168.1.60:9200"]
elasticsearch.username: elastic 
elasticsearch.password: test
